<a href="https://colab.research.google.com/github/Shafeenanasar/Python-Pandas/blob/main/pandas_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [ ]:
a=np.linspace(1,100,10)

In [ ]:
a

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [ ]:
b=pd.Series(a)

In [ ]:
b

0      1.0
1     12.0
2     23.0
3     34.0
4     45.0
5     56.0
6     67.0
7     78.0
8     89.0
9    100.0
dtype: float64

In [ ]:
c={'a':0,'b':1,'c':2}

In [ ]:
d=pd.Series(c)

In [ ]:
d

a    0
b    1
c    2
dtype: int64

# [DataFrame] df

In [ ]:
data={
    "A":[5,6,7],
    "B":[1,7,8],
    "C":[9,5,8]
}

In [ ]:
df=pd.DataFrame(data)

In [ ]:
df

A  B  C
0  5  1  9
1  6  7  5
2  7  8  8

In [ ]:
data1={
    "A":[5],
    "B":[4]
    }

In [ ]:
df1=pd.DataFrame(data1)

In [ ]:
df1

A  B
0  5  4

In [ ]:
arr=np.random.randint(0,100)

In [ ]:
arr

64

In [ ]:
arr=np.random.randint(0,100,20)
arr

array([17, 12, 58, 27, 96, 82,  4, 84, 67, 60, 98, 95, 93, 25, 11, 17, 63,
        7, 81, 29])

In [ ]:
arr=np.random.randint(0,100,(2,3))
arr

array([[20, 42, 15],
       [66, 52,  0]])

In [ ]:
rowname=['mon','tue']
cols=['jan','feb','mar']

In [ ]:
df=pd.DataFrame(arr,index=rowname,columns=cols)
df

jan  feb  mar
mon   20   42   15
tue   66   52    0

In [9]:
path='/content/weather_data.csv'

In [11]:
df=pd.read_csv(path)

In [25]:
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
df.head(3)

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [ ]:
df.tail(2)

day  temperature  windspeed  event
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
df.shape

(6, 4)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   day          6 non-null      object
 1   temperature  6 non-null      int64 
 2   windspeed    6 non-null      int64 
 3   event        6 non-null      object
dtypes: int64(2), object(2)
memory usage: 320.0+ bytes


In [ ]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [ ]:
df.rename(columns={'windspeed':'wind_speed'})

day  temperature  wind_speed  event
0  1/1/2017           32           6   Rain
1  1/2/2017           35           7  Sunny
2  1/3/2017           28           2   Snow
3  1/4/2017           24           7   Snow
4  1/5/2017           32           4   Rain
5  1/6/2017           31           2  Sunny

In [ ]:
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
df.rename(columns={'windspeed':'wind_speed'},inplace=True)
df

day  temperature  wind_speed  event
0  1/1/2017           32           6   Rain
1  1/2/2017           35           7  Sunny
2  1/3/2017           28           2   Snow
3  1/4/2017           24           7   Snow
4  1/5/2017           32           4   Rain
5  1/6/2017           31           2  Sunny

In [ ]:
df.rename(lambda x:x.replace('_','-'),axis='columns')

day  temperature  wind-speed  event
0  1/1/2017           32           6   Rain
1  1/2/2017           35           7  Sunny
2  1/3/2017           28           2   Snow
3  1/4/2017           24           7   Snow
4  1/5/2017           32           4   Rain
5  1/6/2017           31           2  Sunny

In [ ]:
df['day'][df['temperature']==df.temperature.max()]

1    1/2/2017
Name: day, dtype: object

In [ ]:
df['day'][df['temperature']>df.temperature.mean()]

0    1/1/2017
1    1/2/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [ ]:
df[['day','temperature']][df['temperature']>df.temperature.mean()]

day  temperature
0  1/1/2017           32
1  1/2/2017           35
4  1/5/2017           32
5  1/6/2017           31

In [ ]:
df['temperature']>30

0     True
1     True
2    False
3    False
4     True
5     True
Name: temperature, dtype: bool

In [ ]:
df[df['temperature']>30]

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
df['day'][df['temperature']>30]

0    1/1/2017
1    1/2/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [ ]:
df[['day','event']][df['temperature']>30]

day  event
0  1/1/2017   Rain
1  1/2/2017  Sunny
4  1/5/2017   Rain
5  1/6/2017  Sunny

In [ ]:
df[(df['temperature']<30) | (df['windspeed']>5)]

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow

In [ ]:
df[(df['temperature']>30) & (df['windspeed']<5) | (df['temperature']<30) & (df['windspeed']>5)]

day  temperature  windspeed  event
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [26]:
df[['temperature','windspeed']][(df['temperature']>30) & (df['windspeed']<5) | (df['temperature']<30) & (df['windspeed']>5)]

temperature  windspeed
3           24          7
4           32          4
5           31          2

#using loc



loc means position
0th position - event prints

In [12]:
df.loc[0,'event']

'Rain'

In [28]:
df.loc[0:3,['event','windspeed']]

event  windspeed
0   Rain          6
1  Sunny          7
2   Snow          2
3   Snow          7

In [29]:
df.loc[[1,3,4],['event','windspeed']]

event  windspeed
1  Sunny          7
3   Snow          7
4   Rain          4

In [30]:
df.set_index('day',inplace=True)

In [31]:
df

temperature  windspeed  event
day                                    
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

In [38]:
df.reset_index

<bound method DataFrame.reset_index of           temperature  windspeed  event
day                                    
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny>

Extract 2 fields using the specific index

In [34]:
df.loc['1/1/2017':'1/4/2017',['event','temperature']]

event  temperature
day                         
1/1/2017   Rain           32
1/2/2017  Sunny           35
1/3/2017   Snow           28
1/4/2017   Snow           24

OR

In [35]:
df.loc[['1/1/2017','1/2/2017'],['event','temperature','windspeed']]

event  temperature  windspeed
day                                    
1/1/2017   Rain           32          6
1/2/2017  Sunny           35          7

In [3]:
data = pd.DataFrame({'Brand': ['Maruti', 'Hyundai', 'Tata',
                               'Mahindra', 'Maruti', 'Hyundai',
                               'Renault', 'Tata', 'Maruti'],
                     'Year': [2012, 2014, 2011, 2015, 2012,
                              2016, 2014, 2018, 2019],
                     'Kms Driven': [50000, 30000, 60000,
                                    25000, 10000, 46000,
                                    31000, 15000, 12000],
                     'City': ['Gurgaon', 'Delhi', 'Mumbai',
                              'Delhi', 'Mumbai', 'Delhi',
                              'Mumbai', 'Chennai',  'Ghaziabad'],
                     'Mileage':  [28, 27, 25, 26, 28,
                                  29, 24, 21, 24]})

In [7]:
data

Brand  Year  Kms Driven       City  Mileage
0    Maruti  2012       50000    Gurgaon       28
1   Hyundai  2014       30000      Delhi       27
2      Tata  2011       60000     Mumbai       25
3  Mahindra  2015       25000      Delhi       26
4    Maruti  2012       10000     Mumbai       28
5   Hyundai  2016       46000      Delhi       29
6   Renault  2014       31000     Mumbai       24
7      Tata  2018       15000    Chennai       21
8    Maruti  2019       12000  Ghaziabad       24

In [40]:
#brand maruti and mileage greater than 25
data.loc[(data['Brand']=='Maruti') & (data['Mileage']>25)]

Brand  Year  Kms Driven     City  Mileage
0  Maruti  2012       50000  Gurgaon       28
4  Maruti  2012       10000   Mumbai       28

In [5]:
data.loc[(data['Brand']=='Maruti') & (data['Mileage']>25),'City']

0    Gurgaon
4     Mumbai
Name: City, dtype: object

In [14]:
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [13]:
df.iloc[0:3]

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [15]:
df.iloc[0:3,2]

0    6
1    7
2    2
Name: windspeed, dtype: int64

In [16]:
df.iloc[0,2]

6

In [17]:
df.iloc[[1,2,3],[0,1]]

day  temperature
1  1/2/2017           35
2  1/3/2017           28
3  1/4/2017           24

In [19]:
x=df.groupby('event')['temperature'].mean()
x

event
Rain     32.0
Snow     26.0
Sunny    33.0
Name: temperature, dtype: float64

In [20]:
x=df.groupby('event')['temperature'].mean().reset_index()
x

event  temperature
0   Rain         32.0
1   Snow         26.0
2  Sunny         33.0

In [27]:
x=df.groupby('event')['temperature'].mean().sort_values().reset_index()
x

event  temperature
0   Snow         26.0
1   Rain         32.0
2  Sunny         33.0

In [23]:
x=df.groupby('event')['temperature'].agg(['sum','mean']).reset_index()
x

event  sum  mean
0   Rain   64  32.0
1   Snow   52  26.0
2  Sunny   66  33.0

# returns all the values aggregation method of Numerical datas

In [24]:
df.describe()

temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

# Sorting dataframe

**Ascending----default**

In [25]:
df.sort_values(by='temperature')

day  temperature  windspeed  event
3  1/4/2017           24          7   Snow
2  1/3/2017           28          2   Snow
5  1/6/2017           31          2  Sunny
0  1/1/2017           32          6   Rain
4  1/5/2017           32          4   Rain
1  1/2/2017           35          7  Sunny

**Descending**

In [28]:
df.sort_values(by='temperature',ascending=False)

day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
0  1/1/2017           32          6   Rain
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow

In [41]:
def sum(num1,num2):
  add=a+b
  return add

a=int(input('Enter number1'))
b=int(input('Enter number2'))
add=sum(a,b)
print(add)

Enter number12
Enter number23
5


In [42]:
def fun(fare,para):
  if(para<fare):
    print('low fare')
  elif(para>20)&(para<100):
    print('medium fare')
  else:
    print('high fare')

fare=int(input('Enter the fare'))
para=int(input('Enter the parameter'))
fun(fare,para)
print('end')

Enter the fare25
Enter the parameter6
low fare
end
